import {
  bluma,
  brook,
  canelo,
  chelsea,
  chato,
  coco,
  dali,
  dimon,
  humo,
  garbi,
  grelo,
  jalu,
  lambo,
  lira,
  lliria,
  mariano,
  mayo,
  piku,
  pimienta,
  rambo,
  taito,
  taro,
  naira,
  tom,
  honey,
  peggy,
  teide,
  camile,
  aisha,
  pidon,
  bora,
  thanos,
  brownie,
  boniato,
  christmas,
  careTaker,
} from './images/images';

const adopts = [
  {
    id: 1,
    img: dimon,
    name: 'DIMON',
    sexo: 'macho',
    type: 'perro',
    desc: `Este angelito guapo es Dimón, un nene precioso, pastor alemán, que necesita una nueva oportunidad. \n\nDimón tiene unos 3 añitos y es super amoroso y le encanta estar con las personas. Es un amor de nene y muy dulce y bueno. \n\nTambién es sociable con hembras y con machos tranquilotes. \n\nNecesita una familia que se enamore de él, lo adopte y le cambie la vida para siempre. Él lo agradecerá con todo el amor que tiene para dar... \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer.`,
  },
  {
    id: 2,
    img: lliria,
    name: 'LLIRIA',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Lliría es una preciosa gatita parda jovencícima, de añito y poco, que apareció siendo una bebé y todavía busca su hogar... Y no es justo. \n\nMerece una oportunidad. Esta nena es súper cariñosa y se lleva bien con otros gatetes. Aunque al principio es algo miedosa, enseguida coge confianza y se deja querer. \n\nEs muy mimosona, se acerca enseguida a la mano para que la acaricien y empieza a ronronear y a amasar. Le encanta estar panza arriba mientras le dan amor y es suuuper tierna y dulce. \n\nActualmente se encuentra fenomenal en acogida, gracias! Donde está demostrando la gran gata que es. Tan solo necesita un ángel que la salve...y ella le demostrará y entregará todo el amor que tiene para dar. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer.',
  },
  {
    id: 3,
    img: piku,
    name: 'PIKU',
    sexo: 'macho',
    type: 'gato',
    desc: 'Este angelito rubio es Piku, un nene adulto jovencito al que le arrebataron la felicidad con su abandono... Y le prometimos encontrarle una buena familia donde logre ser tan feliz como merece. \n\nNuestro Piku es un rubiazo preciosísimo con unos ojazos que te enamorarán. Es algo timidete al principio, solo necesita un poco de tu amor para abrirse y entregarte su corazón. Anímate a conocer a esta belleza y ya no podrás vivir sin él. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 4,
    img: garbi,
    name: 'GARBI',
    sexo: 'macho',
    type: 'gato',
    desc: 'Este dulce, guapo y tierno gatete es Garbí. Nuestro Garbí es uno de los nenes que llegó en las camadas de abandonaditos de 2021,y todavía sigue esperando a su familia. \n\nGarbí es un gatazo pardito precioso, con un corazón enorme dispuesto a entregar todo su amor, y un carácter que sin duda enamora nada más pasar un ratito junto a él. \n\nNuestro principito es sociable con otros michis, amoroso y un mimoso de las patitas a la cabeza le apasiona estar con las personas y reclamar mucho muuuucho amor, todo el que merece. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 5,
    img: brook,
    name: 'BROOK',
    sexo: 'macho',
    type: 'perro',
    desc: 'Este guapísimo nene es Brook, una preciosidad de animalito y un perro 10 nuestro guaperas es medianito, jovencito y con unas ganas tremendas de encontrar una familia que lo llene de felicidad. \n\nEs muy muy sociable con las personas y le encanta pasear, lo hace super bien, y también jugar con su pelotita. Es enérgico y activo, y tan solo necesita un ángel con quien compartir su vida... ¿Te animas? \n\nTambién es super sociable con otros perretes y le encanta socializar. Te animas a ampliar tu familia con nuestro Brook?. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 6,
    img: taito,
    name: 'TAITO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Taito es un perro buenísimo de 2 añitos aproximadamente, para el que buscamos el mejor de los hogares. \n\nNuestro grandullón apareció abandonado a su suerte y aún así sigue con esa alegría que lo caracteriza y la que nos enamoró. \n\nTaito es un perro activo, muuuy buenazo y cariñoso...le encanta el contacto humano, que lo quieran y den muchos mimos con otros perros es bastante sociable. \n\nSi quieres conocer a nuestra belleza no dudes en contactarnos. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 7,
    img: canelo,
    name: 'CANELO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Nuestro Canelito precioso es uno de los perretes veteranos de la prote y merece un hogar definitivo donde ser feliz toda su vida. \n\nCanelo es un perro precioso, de unos 10 añitos pero con muchísima energía y vitalidad. \n\nLlego a la SPAB con un añito de vida, con miedos e inseguridades que ha ido superando poco a poco gracias a su gran hogar de acogida. \n\nEs un perro cariñoso, buenísimo y muy sociable con otros perros y también con gatos. \n\nCon paciencia y mucho amor, está demostrando que puede con todo y el gran corazón que tiene con muchísimo amor para dar. Canelo puede ser un perro feliz en un hogar donde amen los animales y él lo gradecerá con su amor infinito e incondicional. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 8,
    img: grelo,
    name: 'GRELO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Este perrete apareció hace poquito abandonado y necesitamos para él un buen hogar donde logre recuperar la felicidad que tanto merece.\n\n Grelo es un perrete jóven, amoroso y muy bueno. Con las personas es super cariñoso y con los perretes todavía está en período de sociabilización. \n\nSi quieres ampliar tu familia con este bombón no lo dudes y contáctanos. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 9,
    img: coco,
    name: 'COCO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Coco es un perrete preciosísimo, negro como la noche y todo un buenazo, que necesita un buen hogar donde ser todo lo feliz que merece ser. \n\nNuestro principito es apto con perros, se lleva genial con todos y enseguida se pone a jugar e interactuar con ellos, es muy sociable. También es muy simpático, cariñoso y un amor de perrete de 9 añitos que solo quiere ser feliz.\n\n¿Te animas a ampliar tu familia con él? Te lo agradecerá por siempre. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 10,
    img: taro,
    name: 'TARO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Esta belleza de nene apareció abandonadito y nos llegó a todos al corazón de lo buenazo y noble que es. \n\nTaro es una preciosidad de unos 8 añitos, suuuper cariñoso y apto con todo tipo de prerreter y super amoroso con nenes pequeños. \n\nEs muy tranuilo y dulce. Ideal para una familia con nenes pequños donde se den mutuamente todo el amor del mundo. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 11,
    img: chelsea,
    name: 'CHELSIE',
    sexo: 'hembra',
    type: 'perro',
    desc: 'Nuestra preciosa Chelsie es una nena guapísima, cariñosa y de lo más lista e inteligente, que merece un dulce hogar donde ser muy muy feliz. \n\nChelsea es muy buena, estamos trabajando con ella para su socialización con otros perros y poco a poco va teniendo más amiguetes perrunos.\n\n Nuestra belleza es activa, enérgeica y cruve de labrador. Si quieres concocerla no lo dudes y contáctanos. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 12,
    img: chato,
    name: 'CHATO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Este tierno perrete de 9 añitos merece una casita donde ser nuevamente feliz de momento, necesitamos para él un hogar de acogida. \n\nChato es un perro muy amoroso, cariñoso y dulce con las personas y super sociable con todos los perros. \n\nEs un bomboncito que te necesita... Merece una familia que le de todo el amor del mundo. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 13,
    img: dali,
    name: 'DALÍ',
    sexo: 'macho',
    type: 'gato',
    desc: 'Nuestro Dalí es un tierno y grandullón gatete, tanto como su corazón, que merece un hogar donde ser feliz. \n\nEste nene blanquinegro es precioso, con sus bellos ojazos y esa manchita en su nariz que lo hace único y especial. \n\nDalí es bastante sociable, tanto con las personas como con los demás gatos. Es un pillín y muy juguetón. Te animas a ampliar tu familia con él? \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 14,
    img: mariano,
    name: 'MARIANO',
    sexo: 'macho',
    type: 'gato',
    desc: 'Esta preciosidad de pardito de ojazos verdes merece una oportunidad... Un hogar donde ser feliz toda su vida. \n\nMariano es un gato jóven, bueno y muy cariñoso en cuanto coge un poquito de confianza. Es precioso y te necesita... \n\nAnímate a abrirle las puertas de tu hogar y te lo agradecerá de por vida. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 15,
    img: jalu,
    name: 'JALÚ',
    sexo: 'macho',
    type: 'perro',
    desc: 'Este precioso cachorrito apareció abandonado a su suerte y buscamos para él una buena familia en la que confíe, ame y sea feliz toda su vida. \n\nJalú es todo un buenazo, apto con todos los perros, un amor con las personas y los nenes peques y, como cachorro que es, juguetón y activo. Es muy listo y cariñoso y le encanta estar rodeado de muuucho amor. \n\nAnímate, conócelo y ya no querrás separarte de él. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 16,
    img: lambo,
    name: 'LAMBO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Este bellezón es Lambo, un perrete nacido sobre enero de 2019, que está hecho todo un guaperas con ese pelaje tan bonito que tiene. \n\nLambo es mimoso y dulce. Un amor de nene algo tímido al principio pero luego suuuper cariñoso y dulce. \n\nSe porta genial, es super bueno y se integra muy bien con otros perros y le encanta estar y pasear con ellos. \n\nVen a conocerlo y no te irás sin él. Te lo agradecerá toda la vida... \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 17,
    img: rambo,
    name: 'RAMBO',
    sexo: 'macho',
    type: 'perro',
    desc: 'Esta preciosidad es Rambo, un nene guapísimo color marrón con toquecitos blancos y ojazos de infarto, nacido sobre enero de 2022. \n\nEste guaperas enamora nada más pasar un ratito con él. Es dulce, tierno y cariñoso, algo tímido y en confianza super amoroso. \n\nSe lleva super bien con otros perros. Le encanta pasear en manada y se integra perfectamente. Se porta super bien y, de corazón, que es un perro 10. \n\nAnímate, ven a conocerlo y amplia tu familia con esta belleza. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 18,
    img: pimienta,
    name: 'PIMIENTA',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Esta belleza de blanquita es Pimienta. Apareció abandonada a su suerte y buscamos para ella un buen hogar. Es muy jovencita, nacida sobre marzo del 2023, y te necesita... \n\nPimienta es una nena muy guapa, de pelaje blanco precioso y ojazos, que te enamorará. Es un poco timideta y todavía desconfía un poco, pero estamos seguros de que con paciencia y amor logrará ser muy feliz con su familia. \n\nAnímate, conocela y dale su oportunidad. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 19,
    img: bluma,
    name: 'BLUMA',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Bluma es una bella gatita, negra como la noche y con unos ojazos preciosos, que merece un buen hogar donde ser feliz. \n\nEs muy cariñosa, tranquila y buena. Es algo mayor y merece el calorcito de un hogar el resto de su vida. \n\nBluma es apta con perros y otros gatetes. ¿Quieres hacer feliz a esta nena tan guapísima? \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 20,
    img: lira,
    name: 'LIRA',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Esta pequeña cachorrina tricolor es Lira, una belleza nacida sobre julio de 2023, necesita una familia en la que volver a confiar y que le devuelva la felicidad que le arrebataron al abandonarla... \n\nLira tiene un noble y gran corazón dispuesto a dar mucho amor a quien decida abrirle las puertas de su hogar. Es buena, simpática y muy cariñosa y ronroneadora. \n\nEn cuanto coge un poquito de confianza es super amorosa, solo necesita un ángel a quien demostrárselo. Anímate con ella. \n\nTe aseguramos que seréis felices por siempre. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 21,
    img: mayo,
    name: 'MAYO',
    sexo: 'macho',
    type: 'gato',
    desc: 'Este rubito y blanquito es Mayo, un amorcito de gato que apareció abandonadito y buscamos para él una familia donde logré ser feliz siempre. \n\nMayo es un gatazo de las patitas a la cabeza. Es un amor super cariñoso y juguetón y le encantan los mimitos. \n\nAnímate, conócelo y ya no querrás separarte de su lado. \n\nFotografía realizada por nuestro gran fotógrafo de confianza Enrique Llacer',
  },
  {
    id: 22,
    img: humo,
    name: 'HUMO',
    sexo: 'macho',
    type: 'gato',
    desc: 'Este nene tan precioso es Humo. Apareció abandonadito a su suerte y ahora pasamos a buscarle el mejor de los hogares. \n\nHumo es blanquito y gris ceniza precioso, con unos ojazos verdes que enamoran. Es algo tímido al principio pero en cuanto coge confianza te entrega su corazón y te pide mimos con su dulce ronroneo. \n\nEsta preciosidad merece un hogar que lo ame toda su vida. ¿Le das su oportunidad? \n\nTodos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 23,
    img: naira,
    name: 'NAIRA',
    sexo: 'hembra',
    type: 'perro',
    desc: 'Esta preciosidad es una abuelita de 16 años que necesita ACOGIDA O ADOPCIÓN URGENTE POR FAVOR. \n\nEs una nena muy pero que muy buena y tranquila. Solo necesita amor y cariño y además es súper agradecida y tan dulce... \n\nTambién es súper apta con otros perros y gatos, por lo que si tienes un huequito en tu familia no dudes en darle la oportunidad que tanto merece.',
  },
  {
    id: 24,
    img: tom,
    name: 'TOM',
    sexo: 'macho',
    type: 'perro',
    desc: 'Está belleza de nene es Tom, un angelito que merece su oportunidad. Nació sobre febrero de 2020, y te necesita. \n\nTom es un guapetón muy pero que muy sociable con otros perros. Le encanta relacionarse con ellos y jugar, ¡Es un encanto de perrete! \n\nNuestro Tom es súper cariñoso con las personas y le encanta dar y recibir amor. Es súper dulce y te aseguramos que te hará eternamente feliz si le das la oportunidad que tanto merece. \n\nAnímate y amplia tu familia con él.',
  },
  {
    id: 25,
    img: honey,
    name: 'HONEY',
    sexo: 'hembra',
    type: 'gato',
    desc: '🥰Esta belleza de bebita es Honey, una preciosidad blanca y rubita, de ojazos de infarto, que te robará el corazón. \n\nHoney es dulce, cariñosa y buena. Es súper sociable tanto con personas como con otros gatos. \n\nVen a conocer su enorme corazoncito y ya no querrás separarte de ella. \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 26,
    img: peggy,
    name: 'PEGGY',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Esta pequeña tricolor tan guapa es Peggy, una preciosidad de nena y tan solo una cachorra todavía que merece su oportunidad. Nació sobre verano del 23, y te necesita. \n\nuestra nena es un amor de gata... jovencita, activa y muuyy cariñosa y dulce. Es ronroneadora y le encantan los mimitos. \n\nAnímate, amplia tu familia con ella y no tardarás en enamorarte de esos preciosos ojazos. \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 27,
    img: teide,
    name: 'TEIDE',
    sexo: 'macho',
    type: 'gato',
    desc: 'Esta preciosidad de rubi blanco es Teide, un angelito que merece la oportunidad de su vida...¡una buena familia donde ser feliz! \n\nNuestro niño es todo corazón. Bueno, cariñoso y simpático, que te enamorará totalmente si vienes a conocerlo. \n\nEs un amor de animal, super tierno y guapísimo. ¿Le haces un huequito en tu familia? \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 28,
    img: camile,
    name: 'CAMILE',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Esta gata preciosa es Camile, una peludita bonita, de ojazos azules, que te necesita. \n\nCamile es super mimosa y tranquila. Le encanta estar con las personas y que le den mimos. \n\nVen, conócela y ya no querrás separarte de ella. \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 29,
    img: aisha,
    name: 'AISHA',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Nuestra Aisha es una nena muy buena y cariñosa, aparecida abandonadita hace poquito, que merece que su ángel la salve. \n\nLa nena es un amor de gata, dulce y mimosona y le encanta estar con las personas. \n\nSi vienes a verla te enamorarás de sus ojazos y su preciosa personalidad. Anímate!!! \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 30,
    img: pidon,
    name: 'PIDÓN',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Este preciosísimo blanquinegro es Pidón, un gato bueno a más no poder, dulce y cariñoso, que te necesita. \n\nPidón ha salido + en inmunodeficiencia felina, condición que no le impide llevar una vida totalmente normal y feliz. \n\nRogamos para él un hogar, sin otros gatetes o con gatetes con su misma condición. 😁También podría completar tu familia en caso de que tengas perretes. \n\nEs un amor de animal y merece una oportunidad. Por favor, no dejemos que su condición lo haga invisible. Te necesita!!! \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 31,
    img: bora,
    name: 'BORA',
    sexo: 'hembra',
    type: 'gato',
    desc: 'Esta nena guapa, tierna y dulce es Bora. Apareció hace poquito y nos enamoró con esos ojazos verdes y su precioso pelaje. \n\nBora es una peque muy buena, adulta jovencita y cariñosa en cuanto coge un poquito de confianza. Se deja querer, le encantan los mimos y el contacto con las personas. Es un amor... \n\nAnímate, amplía tu familia peluda con él y seguro que te lo agradecerá por siempre. \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 32,
    img: thanos,
    name: 'THANOS Y VAIANA',
    sexo: 'hembra/macho',
    type: 'gato',
    desc: 'Estos hermanitos aparecieron abandonados hace poco. Thanos macho y Vaiana hembra. \n\nLos dos son muy amorosos y les encanta estar a bracitos. Jugan un montón entre ellos y les encanta la comida húmeda. \n\nVen, conócelos y ya no querrás separarte de ellos. \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
  {
    id: 33,
    img: brownie,
    name: 'BROWNIE',
    sexo: 'macho',
    type: 'gato',
    desc: 'Nuestro Brownie es un gato joven y muy bueno que apareció hace poco y necesita de forma urgente acogida o mejor aún, adopción. \n\nNuestro nene es una panterita preciosa de ojazos que enamoran, tranquilo y cariñosísimo. En su hogar debe ser gato único. \n\nAnímate con él, por favor. Te necesita muchísimo. \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz😸',
  },
  {
    id: 34,
    img: boniato,
    name: 'BONIATO',
    sexo: 'macho',
    type: 'gato',
    desc: 'Este dulce nene, blanquito y rubito es Boniato, un gatete que necesita una oportunidad para ser feliz en un buen hogar. \n\nBoniato es súper bonito, dulce y cariñoso. Tiene una manchita rubia en su nariz que lo hace especial, y esos ojazos verdes que enamoran... \n\nSi quieres ampliar tu familia con un gato buenísimo, mimosón y simpático, Boniato es para ti. ¡Anímate con él! \n\n*Todos nuestros gatos se entregarán en adopción en viviendas protegidas con mosquiteras y redes de balcón, en su caso. Gato protegido, gato seguro y feliz',
  },
];

const destacados = [
  {
    id: 35,
    img: rambo,
    name: 'RAMBO',
    title: 'perros potencialmente perfectos',
    desc: '¿Sabías que durante más de un siglo los pitbulls vivían en todos los hogares donde tenían niños? Los llamaban “los perros niñera” y confiaban plenamente en ellos. A día de hoy, sufren con leyes injustas que hacen más difícil que quieran adoptarlos. Un estudio elaborado en la Facultad de Medicina de la Universidad de Massachuset (y publicado en la prestigiosa revista Science), demuestra que el carácter de un perro no depende de su raza.\n\n ♥️ Adopta con responsabilidad, los perros no nacen siendo agresivos ♥️',
  },
  {
    id: 36,
    img: canelo,
    name: 'CANELO',
    title: 'SESIONES FOTOGRÁFICAS SOLIDARIAS',
    desc: '¿Te gustaría hacerte una sesión de fotos con tu 🐶 o tu 😺 colaborando con la SPAB? Nuestro fotógrafo de confianza Enrique Llacer nos ha propuesto esta gran iniciativa. Por cada sesión fotográfica que escojas a favor nuestra, nos donará el 50% del importe recaudado, ¿a qué es genial? Puedes escoger entre sesión xpress (7 fotos 50€) o sesión plus (10 fotos 80€).¡Anímate y reserva antes del 29/02/24! \n\nMuchísimas gracias una vez más a Enrique por esta gran colaboración🤗',
  },
  {
    id: 37,
    img: garbi,
    name: 'GARBI',
    title: 'IDEA PARA LLEVAR A TU GATO EN EL TRANSPORTÍN DE FORMA SEGURA',
    desc: '¿Qué os parece esta idea para llevar a tu gatete de forma segura cuando salgáis con él en su transportín? 🤗 De esta manera no se asustará al ver el exterior de su hogar dentro del transportín y se reducirán las posibilidades de que pueda salirse del mismo. Os animamos a que lo probéis❤ \n\nGato seguro, gato feliz🐱🐈😺',
  },
  {
    id: 38,
    img: chato,
    name: 'chato',
    title: 'LA IMPORTANCIA DE LOS HOGARES DE ACOGIDA',
    desc: 'Mirad la diferencia de nuestro precioso Taro cuando llegó en la primera foto… Y ya unos días en su hogar de acogida, en la segunda foto🥰 Las casas de acogida son muy importantes, hacen de puente entre las protectoras de animales y las futuras adopciones🙏 \n\nSer casa de acogida cambia vidas…Un hogar y mucho amor les cambia la vida❤',
  },
  {
    id: 39,
    img: humo,
    name: 'humo',
    title: 'ESTE INVIERNO REVISA TU COCHE',
    desc: 'Este invierno ❄ REVISA TU COCHE 🚗 antes de arrancar. Con la llegada del frío, los michis 🐱🐈😺 se refugian en las ruedas, debajo de los coches e incluso en los motores. Por favor, da unos toquecitos en el capó de tu coche antes de arrancar. Podrás salvar vidas y también evitar accidentes. \n\nGRACIAS💜',
  },
  {
    id: 40,
    img: christmas,
    name: 'christmas',
    title: '¡FELIZ NAVIDAD Y PROSPERO 2024!',
    desc: 'El equipo de la SPAB os queremos desear una feliz Navidad y un Próspero Año Nuevo 2024✨ Por un año con muchísimas adopciones y abandono 0🙏 \n\nFELICES FIESTAS💗🎄',
  },
  {
    id: 41,
    img: careTaker,
    name: 'careTaker',
    title: '¡Nuestros rescatadores!',
    desc: 'Si alguien puede encontrar y rescatar a cualquier animal que esté en peligro, estos son Maria José, Álex y Vicky, nuestros rescatadores favoritos. Encargados de las colonias felinas y de acudir a cualquier lugar donde se haya visto un animal nuevo, que hayan abandonado o se haya escapado. \n\nEstén donde estén y cueste lo que cueste estos tres valientes consiguen hacerse con todos. No descansan ni un minuto, da igual el día, el lugar, de día o de noche; siempre están preparados con sus armas favoritas: una jaula trampa, un transportín y la red. Lloviendo, a pleno sol, con frío, con calor, en tejados, en bajos, en matorrales, en piscinas… sea donde sea y cueste el tiempo que cueste, nunca se rinden, hacen todo lo posible por darles una vida mejor a aquellos que no tienen voz. ',
  },
];

const chartData = [
  {
    id: 1,
    year: 2018,
    adopciones: 149,
  },
  {
    id: 2,
    year: 2019,
    adopciones: 161,
  },
  {
    id: 3,
    year: 2020,
    adopciones: 131,
  },
  {
    id: 4,
    year: 2021,
    adopciones: 112,
  },
  {
    id: 5,
    year: 2022,
    adopciones: 109,
  },
  {
    id: 6,
    year: 2023,
    adopciones: 72,
  },
  {
    id: 7,
    year: 2024,
    adopciones: 78,
  },
];

export { adopts, destacados, chartData };
